include: package:flutter_lints/flutter.yaml

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
    - duplicated-code

  metrics:
    cyclomatic-complexity: 10
    maximum-nesting-level: 3
    number-of-parameters: 4
    source-lines-of-code: 40
    number-of-methods: 10
    weight-of-class: 0.33
    lines-of-executable-code: 30

  rules:
    - avoid-non-null-assertion
    - avoid-unused-parameters
    - prefer-trailing-comma
    - no-boolean-literal-compare
    - no-equal-then-else
    - avoid-dynamic
    - member-ordering
    - newline-before-return
    - prefer-moving-to-variable
    - avoid-global-state
    - prefer-first
    - prefer-conditional-expressions

  exclude:
    - test/**
    - lib/generated/**
    - lib/**/*.g.dart
